// src/app/layout.tsx
import RefineApp from "./RefineApp";
import { cookies } from "next/headers";
import { Metadata } from "next";
import React from "react";

export const metadata: Metadata = {
  title: "Refine",
  description: "Generated by create refine app",
  icons: { icon: "/favicon.ico" },
};

export default function RootLayout({ children }: { children: React.ReactNode }) {
  const theme = cookies().get("theme")?.value;
  const defaultMode = theme === "dark" ? "dark" : "light";

  return (
    <html lang="en">
    <body>
    {/* pass the default theme-mode into the client component */}
    <RefineApp defaultMode={defaultMode}>{children}</RefineApp>
    </body>
    </html>
  );
}
